name: BilzerShop
version: '1.0-SNAPSHOT'
main: fr.bilscript.bilzershop.BilzerShop
api-version: '1.20'
load: STARTUP
authors: [ Bilskoww ]

commands:
  eco:
    description: eco cmd
    aliases:
      - money
      - economy
    #permission: bilzershop.admin
    #permission-message: bouffon va
  pay:
    description: pay pr payer abuse zinc reflechi
  shop:
    description: pour achetar